<a href="https://colab.research.google.com/github/RealMyeong/AIFFELTHON/blob/main/SBShim/sentence_separation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import json

In [18]:
train = pd.read_csv('/content/drive/MyDrive/공부/AIFFELTHON/data/train.csv')

UnicodeDecodeError: ignored

In [37]:
mask = pd.read_csv('/content/drive/MyDrive/공부/AIFFELTHON/data/train_mask.csv', encoding='utf-8')

In [19]:
train['count'] = train.apply(lambda x : x['conversation'].count('\n') + 1 , axis = 1 )

In [43]:
train

,idx,class,conversation,count
0,0,협박 대화,지금 너 스스로를 죽여달라고 애원하는 것인가?\n 아닙니다. 죄송합니다.\n 죽을 ...,10
1,1,협박 대화,길동경찰서입니다.\n9시 40분 마트에 폭발물을 설치할거다.\n네?\n똑바로 들어 ...,10
2,2,기타 괴롭힘 대화,너 되게 귀여운거 알지? 나보다 작은 남자는 첨봤어.\n그만해. 니들 놀리는거 재미...,10
3,3,갈취 대화,어이 거기\n예??\n너 말이야 너. 이리 오라고\n무슨 일.\n너 옷 좋아보인다?...,11
4,4,갈취 대화,저기요 혹시 날이 너무 뜨겁잖아요? 저희 회사에서 이 선크림 파는데 한 번 손등에 ...,12
...,...,...,...,...
3945,3945,기타 괴롭힘 대화,준하야 넌 대가리가 왜이렇게 크냐?\n내 머리가 뭐.\n밥먹으면 대가리만 크냐 너는...,11
3946,3946,갈취 대화,내가 지금 너 아들 김길준 데리고 있어. 살리고 싶으면 계좌에 1억만 보내\n예.?...,10
3947,3947,직장 내 괴롭힘 대화,나는 씨 같은 사람 보면 참 신기하더라. 어떻게 저렇게 살지.\n왜 그래. 들리겠어...,11
3948,3948,갈취 대화,누구맘대로 여기서 장사하래?\n이게 무슨일입니까?\n남의 구역에서 장사하려면 자릿세...,10
3949,3949,직장 내 괴롭힘 대화,희정씨\n네?\n주말에 시간이 넘쳐나나봐\n갑자기 왜그러세요?\n손이 빤짝빤짝 네일...,10

In [26]:
mask

    1  2  3  4  5  6  7  8  9  10   11   12
0   1  2  1  2  1  2  1  2  1   2  NaN  NaN
1   2  1  2  1  2  1  2  1  2   1  NaN  NaN
2   1  2  1  1  2  1  2  1  1   2  NaN  NaN
3   1  2  1  2  1  1  2  1  1   1  2.0  NaN
4   1  2  1  2  1  2  1  2  1   2  1.0  2.0
5   1  2  1  2  1  2  1  2  1   2  NaN  NaN
6   2  1  2  1  2  1  2  1  2   1  2.0  1.0
7   1  1  2  1  1  2  1  2  1   2  1.0  NaN
8   1  2  1  2  1  2  1  2  1   2  NaN  NaN
9   1  2  1  2  1  2  1  2  1   2  NaN  NaN
10  2  1  2  1  2  1  2  1  2   1  2.0  1.0

In [36]:

s = str(1)
mask[s][0]

TypeError: ignored

In [44]:
all_sentence = []
all_labels = []

for i in range(len(mask)):  
  talker1 = []
  talker2 = []
  mask = train['mask'][i]
  sen = train['conversation'][i].split('\n')
  for j in range(12):
    m = (mask[str(j + 1)][i])
    if m == 1:
      talker1.append(sen[j])
    elif m == 2:
      talker2.append(sen[j])
    elif m == None:
      continue
  reu_sen = '\n'.join(talker1)
  label = train['class'][i] + ' 위협자'

  all_sentence.append(reu_sen)
  all_labels.append(label)

  reu_sen = '\n'.join(talker2)
  label = train['class'][i] + ' 피해자'
  
  all_sentence.append(reu_sen)
  all_labels.append(label)

In [47]:
#new_data = pd.DataFrame(data = [[all_sentence, all_labels]], columns = ['conversation', 'class'])
new_data = pd.DataFrame({'conversation':all_sentence, 'class':all_labels})

In [50]:
train.head(10)

   idx        class                                       conversation  count
0    0        협박 대화  지금 너 스스로를 죽여달라고 애원하는 것인가?\n 아닙니다. 죄송합니다.\n 죽을 ...     10
1    1        협박 대화  길동경찰서입니다.\n9시 40분 마트에 폭발물을 설치할거다.\n네?\n똑바로 들어 ...     10
2    2    기타 괴롭힘 대화  너 되게 귀여운거 알지? 나보다 작은 남자는 첨봤어.\n그만해. 니들 놀리는거 재미...     10
3    3        갈취 대화  어이 거기\n예??\n너 말이야 너. 이리 오라고\n무슨 일.\n너 옷 좋아보인다?...     11
4    4        갈취 대화  저기요 혹시 날이 너무 뜨겁잖아요? 저희 회사에서 이 선크림 파는데 한 번 손등에 ...     12
5    5  직장 내 괴롭힘 대화  나 이틀뒤에 가나다 음식점 예약좀 해줘. 저녁7시로.\n가나다 음식점이요.?\n응....     10
6    6    기타 괴롭힘 대화  35번 손님 아이스커피 두잔나왔습니다\n아이스커피? \n네 맛있게드세요\n저기요 아...     12
7    7    기타 괴롭힘 대화  경비아저씨 내차에 경고장 붙였어요?\n내가 여기 몇년째 사는데 아직도 내차인줄 모르...     11
8    8    기타 괴롭힘 대화  이거 할인 된다면서요\n 확인해보겠습니다\n 아까 저 시람은 할인 해주던데\n 네 ...     10
9    9        갈취 대화  자네 세금계산서 보내준 거 메일이랑 수치가 다르던데?\n그게.\n얼마나 해먹었어? ...     10

In [48]:
new_data

                                         conversation            class
0   지금 너 스스로를 죽여달라고 애원하는 것인가?\n 죽을 거면 혼자 죽지 우리까지 사...        협박 대화 위협자
1    아닙니다. 죄송합니다.\n 정말 잘못했습니다.\n 죄송합니다. 정말 잘못했습니다....        협박 대화 피해자
2   9시 40분 마트에 폭발물을 설치할거다.\n똑바로 들어 한번만 더 얘기한다.\n9시...        협박 대화 위협자
3   길동경찰서입니다.\n네?\n장난전화 걸지 마시죠. \n장난전화는 업무방해죄에 해당됩...        협박 대화 피해자
4   너 되게 귀여운거 알지? 나보다 작은 남자는 첨봤어.\n지영아 너가 키 160이지?...    기타 괴롭힘 대화 위협자
5   그만해. 니들 놀리는거 재미없어.\n니들이 나 작은데 보태준거 있냐?\n더이상 하지...    기타 괴롭힘 대화 피해자
6   어이 거기\n너 말이야 너. 이리 오라고\n너 옷 좋아보인다?\n얘 돈 좀 있나봐\...        갈취 대화 위협자
7                      예??\n무슨 일.\n아니에요.돈 없어요\n정말 없어요        갈취 대화 피해자
8   저기요 혹시 날이 너무 뜨겁잖아요? 저희 회사에서 이 선크림 파는데 한 번 손등에 ...        갈취 대화 위협자
9   아 진짜요? 안 그래도 선크림 필요해서 알아보던 중인데 한 번 발라 볼게요!\n음....        갈취 대화 피해자
10  나 이틀뒤에 가나다 음식점 예약좀 해줘. 저녁7시로.\n응. 남자친구 부모님한테 인...  직장 내 괴롭힘 대화 위협자
11  가나다 음식점이요.?\n저.팀장님. 저도 월 말 프로젝트로 정신없어서.죄송하지만.\...  직장 내 괴롭힘 대화 피해자
12  아이스커피? \n저기요 아가씨 나는 아아스 시킨적이 없는데?\n내가 그랫어? \n아...    기타 괴롭힘 대화 위협자
13  35번 손님 아이스커피 두잔나왔습니다\n네 맛있게드세요\n아 분명 오늘 날이 더우시...    기타 괴롭힘 대화 피해자
14  경비아저씨 내차에 경고장 붙였어요?\n내가 여기 몇년째 사는데 아직도 내차인줄 모르...    기타 괴롭힘 대화 위협자
15  입주민께서 정해진 주차자리가 아닌 통로에 계속 주차하셔서 입주민들 항의가 계속 들어...    기타 괴롭힘 대화 피해자
16  이거 할인 된다면서요\n 아까 저 시람은 할인 해주던데\n 고객을 차별하는 거에요?...    기타 괴롭힘 대화 위협자
17   확인해보겠습니다\n 네 저 손님은 고객님이십니다\n 저희는 등급제로 운영돼서 그런...    기타 괴롭힘 대화 피해자
18  자네 세금계산서 보내준 거 메일이랑 수치가 다르던데?\n얼마나 해먹었어? 괜찮아. ...        갈취 대화 위협자
19  그게.\n회사에는 비밀로 해주십시오.\n어느정도.생각하시죠?\n그건 너무 많습니다....        갈취 대화 피해자
20  말보르 레드 하나.\n여기 사장은 없어?\n지금부터 내 말 잘들어. 여기 주머니에 ...        갈취 대화 위협자
21  네 뭐 드릴까요?\n네. 여기요!\n네 사장님 지금 안계세요. 뭐 .찾으세요?\n ...        갈취 대화 피해자